- include_vars: "{{ item }}"
  with_items:
    - vtiger6.yml
    - version.yml
  tags:
    - always

# Install vTiger - executed by Dockerfile
- name: vTiger | Installation
  include: install.yml

# Configure vTiger - executed on container start
- name: vTiger | Configuration
  include: configure.yml
  tags:
    - configuration